//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectrumWebForms
{
    public partial class AdminPanelPage
    {
        protected global::System.Web.UI.WebControls.Literal AdminNameLiteral;

        protected global::System.Web.UI.WebControls.Literal MemberCountLiteral;

        protected global::System.Web.UI.WebControls.Literal EventCountLiteral;

        protected global::System.Web.UI.WebControls.Literal UpcomingCountLiteral;

        protected global::System.Web.UI.WebControls.Panel MessagePanel;

        protected global::System.Web.UI.WebControls.Literal MessageLiteral;

        protected global::System.Web.UI.WebControls.HiddenField MemberIdHiddenField;

        protected global::System.Web.UI.WebControls.TextBox MemberFullNameTextBox;

        protected global::System.Web.UI.WebControls.TextBox MemberPositionTextBox;

        protected global::System.Web.UI.WebControls.TextBox MemberDepartmentTextBox;

        protected global::System.Web.UI.WebControls.TextBox MemberEmailTextBox;

        protected global::System.Web.UI.WebControls.TextBox MemberPhoneTextBox;

        protected global::System.Web.UI.WebControls.TextBox MemberPhotoUrlTextBox;

        protected global::System.Web.UI.WebControls.TextBox MemberBioTextBox;

        protected global::System.Web.UI.WebControls.CheckBox MemberActiveCheckBox;

        protected global::System.Web.UI.WebControls.Button MemberSaveButton;

        protected global::System.Web.UI.WebControls.Button MemberClearButton;

        protected global::System.Web.UI.WebControls.GridView MembersGridView;

        protected global::System.Web.UI.WebControls.HiddenField EventIdHiddenField;

        protected global::System.Web.UI.WebControls.TextBox EventSlugTextBox;

        protected global::System.Web.UI.WebControls.TextBox EventTitleTextBox;

        protected global::System.Web.UI.WebControls.TextBox EventDateTextBox;

        protected global::System.Web.UI.WebControls.TextBox EventVenueTextBox;

        protected global::System.Web.UI.WebControls.TextBox EventFormatTextBox;

        protected global::System.Web.UI.WebControls.TextBox EventFeeTextBox;

        protected global::System.Web.UI.WebControls.TextBox EventTaglineTextBox;

        protected global::System.Web.UI.WebControls.TextBox EventSummaryTextBox;

        protected global::System.Web.UI.WebControls.TextBox EventEligibilityTextBox;

        protected global::System.Web.UI.WebControls.TextBox EventPaymentNoteTextBox;

        protected global::System.Web.UI.WebControls.TextBox EventGuidelinesTextBox;

        protected global::System.Web.UI.WebControls.TextBox EventBackgroundUrlTextBox;

        protected global::System.Web.UI.WebControls.CheckBox EventUpcomingCheckBox;

        protected global::System.Web.UI.WebControls.CheckBox EventActiveCheckBox;

        protected global::System.Web.UI.WebControls.Button EventSaveButton;

        protected global::System.Web.UI.WebControls.Button EventClearButton;

        protected global::System.Web.UI.WebControls.GridView EventsGridView;
    }
}
