//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectrumWebForms
{
    public partial class DefaultPage
    {
        protected global::System.Web.UI.WebControls.Repeater UpcomingEventsRepeater;

        protected global::System.Web.UI.WebControls.Repeater MembersRepeater;
    }
}