//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectrumWebForms
{
    public partial class LoginPage
    {
        protected global::System.Web.UI.WebControls.Panel MessagePanel;

        protected global::System.Web.UI.WebControls.Literal MessageLiteral;

        protected global::System.Web.UI.WebControls.Panel SuccessPanel;

        protected global::System.Web.UI.WebControls.Literal SuccessLiteral;

        protected global::System.Web.UI.WebControls.TextBox UsernameTextBox;

        protected global::System.Web.UI.WebControls.TextBox PasswordTextBox;

        protected global::System.Web.UI.WebControls.Button LoginButton;
    }
}
