//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectrumWebForms
{
    public partial class RegistrationPage
    {
        protected global::System.Web.UI.WebControls.Literal PageTitleLiteral;
        protected global::System.Web.UI.WebControls.Literal EventTitleLiteral;
        protected global::System.Web.UI.WebControls.Literal EventFormatLabelLiteral;
        protected global::System.Web.UI.WebControls.Literal EligibilityLabelLiteral;
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;
        protected global::System.Web.UI.WebControls.Literal ErrorMessageLiteral;
        protected global::System.Web.UI.WebControls.Panel SuccessPanel;
        protected global::System.Web.UI.WebControls.Literal RegistrationIdLiteral;
        protected global::System.Web.UI.WebControls.Literal SubmittedAtLiteral;
        protected global::System.Web.UI.WebControls.Literal EventLiteral;
        protected global::System.Web.UI.WebControls.Literal EventFormatLiteral;
        protected global::System.Web.UI.WebControls.Literal FullNameLiteral;
        protected global::System.Web.UI.WebControls.Literal EmailLiteral;
        protected global::System.Web.UI.WebControls.Literal InstitutionLiteral;
        protected global::System.Web.UI.WebControls.Literal DepartmentLiteral;
        protected global::System.Web.UI.WebControls.Literal AcademicYearLiteral;
        protected global::System.Web.UI.WebControls.Literal PaymentMethodLiteral;
        protected global::System.Web.UI.WebControls.Literal PaymentReferenceLiteral;
        protected global::System.Web.UI.WebControls.Literal MotivationLiteral;
        protected global::System.Web.UI.WebControls.Panel FormPanel;
        protected global::System.Web.UI.WebControls.Panel InstitutionWrap;
        protected global::System.Web.UI.WebControls.TextBox FullNameTextBox;
        protected global::System.Web.UI.WebControls.TextBox EmailTextBox;
        protected global::System.Web.UI.WebControls.TextBox DepartmentTextBox;
        protected global::System.Web.UI.WebControls.DropDownList AcademicYearDropDown;
        protected global::System.Web.UI.WebControls.TextBox MotivationTextBox;
        protected global::System.Web.UI.WebControls.TextBox InstitutionNameTextBox;
        protected global::System.Web.UI.WebControls.DropDownList PaymentMethodDropDown;
        protected global::System.Web.UI.WebControls.TextBox PaymentReferenceTextBox;
        protected global::System.Web.UI.WebControls.Button SubmitButton;
    }
}